name: CI

on:
  workflow_dispatch:

jobs:
  Pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and Run Pytest
        run: |
          export SETUPTOOLS_USE_DISTUTILS=stdlib
          pip3 install pytest
          python3 -m pytest -s
